name: 每日更新招标信息RSS

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 如果有依赖安装与构建步骤，请在这里补充
      # - name: 安装依赖
      #   run: pip install -r requirements.txt
      # - name: 运行构建脚本
      #   run: python your_script.py

      # 假设输出目录为 output，如有不同请修改
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # 如果你是首次部署，action 会自动帮你创建 gh-pages 分支
